version: "3.7"
services:
  web:
    build: .
    command: ["./wait-for-it.sh", "pgdb:5432", "--timeout=90", "--", "node", "./bin/www"]
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - pgdb
    environment:
      - DATABASE_URL=postgres://group16:abc123@pgdb:5432/postgres
    restart: on-failure

  pgdb:
    container_name: postgres
    restart: always
    image: postgres:11.0-alpine
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'group16'
      POSTGRES_PASSWORD: 'abc123'
      POSTGRES_DB: 'postgres'
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -d postgres -U group16"]
      interval: 10s
      timeout: 5s
      retries: 5

  py:
    container_name: python
    image: continuumio/anaconda3:latest
    volumes:
      - ./docker:/home/py/anaconda
    restart: on-failure


      
